### PR TITLE
Make seperated terms as word selectable

### PR DESCRIPTION
**Pull request by ralferlebach**
There are words, that are seperated by spaces like "cat content" or "high speed camera". So, it should be possible to bracket those multi word terms with *'s as well.

### CODE REVIEW

**Comment by otacke** [comment]
@ralferlebach This has been discussed a couple of times on the H5P forum: You now give away correct answers. Any markable text snippet that contains more than one word can safely be chosen as it must be correct.

_"We should fix this in a way that doesn't reveal that a phrase is correct. If for instance only phrases that are correct was possible to mark by clicking one of the words in the phrase users could find the correct phrases by clicking all the words. We might solve this by allowing for marking up wrong phrases as well, or have the user actually mark the text to select it, [...]"_ (https://h5p.org/comment/2643#comment-2643)

**Comment by ralferlebach** [comment]
Ok. Than, there should be a solution like the &#32-hack. I close this PR and will come forward with a solution that tackles this approach as well.

**Comment by rezeau** [comment]
@otacke 
In order to not reveal the correctness of "blocks of words", simply removing this CSS rule would make all words selectable without displaying anything. Would that be acceptable?
Remove this CSS rule:
.h5p-mark-the-words .h5p-word-selectable-words:not(.h5p-disable-hover) [role="option"]:hover {
  box-shadow: inset 0px 0px 0px 2px #cee0f4;
}

**Comment by otacke** [comment]
@rezeau That's not up to me to decide as I thought you'd know. I am not part of the H5P core team. I just hinted that this topic was discussed already. But if you want my opinion: Wouldn't removing the hover not just shift the problem? Instead of hovering over the words as a student I'd now have to click every word (group) once in order to see if there's more than one word highlighted.

**Pull request closed without merging**
